# SPDX-License-Identifier: GPL-2.0
snd-soc-si468x-objs := si468x.o
snd-soc-ssm2518-objs := ssm2518.o

obj-$(CONFIG_SND_SOC_SI468X)	+= snd-soc-si468x.o
obj-$(CONFIG_SND_SOC_SSM2518)	+= snd-soc-ssm2518.o
