# SPDX-License-Identifier: GPL-2.0
#
# Makefile for multifunction miscellaneous devices
#

si468x-core-y := si468x-cmd.o si468x-prop.o

obj-$(CONFIG_MFD_SI468X_CORE)	+= si468x-core.o
obj-$(CONFIG_MFD_SI468X_I2C)	+= si468x-i2c.o
obj-$(CONFIG_MFD_SI468X_SPI)	+= si468x-spi.o
