// SPDX-License-Identifier: GPL-2.0-only
/*
 * drivers/mfd/si468x-prop.c -- Subroutines to access
 * properties of si468x chips
 *
 * Copyright (C) 2020 HTL Steyr - Austria
 * Copyright (C) 2020 Franz Parzer
 * based on the si476x driver of 
 * Copyright (C) 2012 Innovative Converged Devices(ICD)
 * Copyright (C) 2013 Andrey Smirnov
 *
 * Author: Franz Parzer <rpi-receiver@htl-steyr.ac.at>
 * Author: Andrey Smirnov <andrew.smirnov@gmail.com>
 */
#include <linux/module.h>

#include <linux/mfd/si468x-core.h>

static const struct regmap_range si468x_common_reg_ranges[] = {
		regmap_reg_range(SI468X_PROP_INT_CTL_ENABLE,
			SI468X_PROP_INT_CTL_REPEAT),
		regmap_reg_range(SI468X_PROP_DIGITAL_IO_OUTPUT_SELECT,
			SI468X_PROP_DIGITAL_IO_OUTPUT_FORMAT_OVERRIDES_4),
		regmap_reg_range(SI468X_PROP_AUDIO_ANALOG_VOLUME,
			SI468X_PROP_AUDIO_OUTPUT_CONFIG),
		regmap_reg_range(SI468X_PROP_PIN_CONFIG_ENABLE,
			SI468X_PROP_PIN_CONFIG_ENABLE),
		regmap_reg_range(SI468X_PROP_WAKE_TONE_ENABLE,
			SI468X_PROP_WAKE_TONE_AMPLITUDE),
		regmap_reg_range(SI468X_PROP_DIGITAL_SERVICE_INT_SOURCE,
			SI468X_PROP_DIGITAL_SERVICE_RESTART_DELAY),
};

static const struct regmap_access_table si468x_common_write_ranges_table = {
		.yes_ranges     = si468x_common_reg_ranges,
		.n_yes_ranges   = ARRAY_SIZE(si468x_common_reg_ranges),
};

static const struct reg_default si468x_common_reg_defaults[] = {
		{ SI468X_PROP_INT_CTL_ENABLE, 0x0000 },
		{ SI468X_PROP_INT_CTL_REPEAT, 0x0000 },
		{ SI468X_PROP_DIGITAL_IO_OUTPUT_SELECT, 0 },
		{ SI468X_PROP_DIGITAL_IO_OUTPUT_SAMPLE_RATE, 48000 },
		{ SI468X_PROP_DIGITAL_IO_OUTPUT_FORMAT, 0x1800 },
		{ SI468X_PROP_DIGITAL_IO_OUTPUT_FORMAT_OVERRIDES_1, 0 },
		{ SI468X_PROP_DIGITAL_IO_OUTPUT_FORMAT_OVERRIDES_2, 0 },
		{ SI468X_PROP_DIGITAL_IO_OUTPUT_FORMAT_OVERRIDES_3, 0 },
		{ SI468X_PROP_DIGITAL_IO_OUTPUT_FORMAT_OVERRIDES_4, 0 },
		{ SI468X_PROP_AUDIO_ANALOG_VOLUME, 63 },
		{ SI468X_PROP_AUDIO_MUTE, 0x0000 },
		{ SI468X_PROP_AUDIO_OUTPUT_CONFIG, 0x0000 },
		{ SI468X_PROP_PIN_CONFIG_ENABLE, 0x8001 },
		{ SI468X_PROP_WAKE_TONE_ENABLE, 0 },
		{ SI468X_PROP_WAKE_TONE_PERIOD, 250 },
		{ SI468X_PROP_WAKE_TONE_FREQ, 750 },
		{ SI468X_PROP_WAKE_TONE_AMPLITUDE, 8 },
		{ SI468X_PROP_DIGITAL_SERVICE_INT_SOURCE, 0x0000 },
		{ SI468X_PROP_DIGITAL_SERVICE_RESTART_DELAY, 8000 },
};

static const struct regmap_range si468x_am_reg_ranges[] = {
		regmap_reg_range(SI468X_PROP_AM_AVC_MIN_GAIN,
			SI468X_PROP_AM_AVC_MAX_GAIN),
		regmap_reg_range(SI468X_PROP_AGC_RF_THRESHOLD,
			SI468X_PROP_AGC_RF_THRESHOLD),
		regmap_reg_range(SI468X_PROP_AM_CHBW_SQ_LIMITS,
			SI468X_PROP_AM_CHBW_OVERRIDE_BW),
		regmap_reg_range(SI468X_PROP_AM_SEEK_BAND_BOTTOM,
			SI468X_PROP_AM_SEEK_FREQUENCY_SPACING),
		regmap_reg_range(SI468X_PROP_AM_VALID_MAX_TUNE_ERROR,
			SI468X_PROP_AM_VALID_HDLEVEL_THRESHOLD),
		regmap_reg_range(SI468X_PROP_AM_RSQ_INTERRUPT_SOURCE,
			SI468X_PROP_AM_RSQ_HDLEVEL_LOW_THRESHOLD),
		regmap_reg_range(SI468X_PROP_AM_ACF_INTERRUPT_SOURCE,
			SI468X_PROP_AM_ACF_CONTROL_SOURCE),
		regmap_reg_range(SI468X_PROP_AM_SOFTMUTE_SQ_LIMITS,
			SI468X_PROP_AM_SOFTMUTE_SQ_RELEASE_TIME),
		regmap_reg_range(SI468X_PROP_AM_HIGHCUT_SQ_LIMITS,
			SI468X_PROP_AM_HIGHCUT_SQ_RELEASE_TIME),
		regmap_reg_range(SI468X_PROP_AM_DEMOD_AFC_RANGE,
			SI468X_PROP_AM_DEMOD_AFC_RANGE),
		regmap_reg_range(SI468X_PROP_HD_BLEND_OPTIONS,
			SI468X_PROP_HD_BLEND_HD_TO_ANALOG_TRANSITION_TIME),
		regmap_reg_range(SI468X_PROP_HD_BLEND_DYNAMIC_GAIN,
			SI468X_PROP_HD_BLEND_DYNAMIC_GAIN),
		regmap_reg_range(SI468X_PROP_HD_BLEND_DECISION_ANA_TO_DIG_THRESHOLD,
			SI468X_PROP_HD_BLEND_SERV_LOSS_NOISE_AUDIO_START_DELAY),
		regmap_reg_range(SI468X_PROP_HD_BLEND_BWM_CTRL_THRES,
			SI468X_PROP_HD_BLEND_BWM_BLEND_RAMP_DOWN_TIME),
		regmap_reg_range(SI468X_PROP_HD_DIGRAD_INTERRUPT_SOURCE,
			SI468X_PROP_HD_DIGRAD_CDNR_HIGH_THRESHOLD),
		regmap_reg_range(SI468X_PROP_HD_EVENT_INTERRUPT_SOURCE,
			SI468X_PROP_HD_EVENT_ALERT_CONFIG),
		regmap_reg_range(SI468X_PROP_HD_ACF_INTERRUPT_SOURCE,
			SI468X_PROP_HD_ACF_STEREO_SEP_TOLERANCE),
		regmap_reg_range(SI468X_PROP_HD_PSD_ENABLE,
			SI468X_PROP_HD_PSD_FIELD_MASK),
		regmap_reg_range(SI468X_PROP_HD_AUDIO_CTRL_FRAME_DELAY,
			SI468X_PROP_HD_AUDIO_CTRL_BALL_GAME_ENABLE),
		regmap_reg_range(SI468X_PROP_HD_CODEC_MODE_0_BLEND_THRESHOLD,
			SI468X_PROP_HD_CODEC_MODE_3_BLEND_RATE),
		regmap_reg_range(SI468X_PROP_HD_EZBLEND_ENABLE,
			SI468X_PROP_HD_EZBLEND_SPS_BLEND_RATE),
		regmap_reg_range(SI468X_PROP_HD_ENHANCED_STREAM_HOLDOFF_CONFIG,
			SI468X_PROP_HD_ENHANCED_STREAM_HOLDOFF_THRESHOLDS),
		regmap_reg_range(SI468X_PROP_HD_TEST_BER_CONFIG,
			SI468X_PROP_HD_TEST_BER_CONFIG),
};

static const struct regmap_access_table si468x_am_write_ranges_table = {
		.yes_ranges     = si468x_am_reg_ranges,
		.n_yes_ranges   = ARRAY_SIZE(si468x_am_reg_ranges),
};

static const struct reg_default si468x_am_reg_defaults[] = {
		{ SI468X_PROP_AM_AVC_MIN_GAIN, -2048 },
		{ SI468X_PROP_AM_AVC_MAX_GAIN, 10220 },
		{ SI468X_PROP_AGC_RF_THRESHOLD, 0 },
		{ SI468X_PROP_AM_CHBW_SQ_LIMITS, 0x1e0f },
		{ SI468X_PROP_AM_CHBW_SQ_CHBW, 0x2314 },
		{ SI468X_PROP_AM_CHBW_SQ_WIDENING_TIME, 2048 },
		{ SI468X_PROP_AM_CHBW_SQ_NARROWING_TIME, 16 },
		{ SI468X_PROP_AM_CHBW_OVERRIDE_BW, 0 },
		{ SI468X_PROP_AM_SEEK_BAND_BOTTOM, 520 },
		{ SI468X_PROP_AM_SEEK_BAND_TOP, 1710 },
		{ SI468X_PROP_AM_SEEK_FREQUENCY_SPACING, 10 },
		{ SI468X_PROP_AM_VALID_MAX_TUNE_ERROR, 75 },
		{ SI468X_PROP_AM_VALID_RSSI_TIME, 8 },
		{ SI468X_PROP_AM_VALID_RSSI_THRESHOLD, 35 },
		{ SI468X_PROP_AM_VALID_SNR_TIME, 40 },
		{ SI468X_PROP_AM_VALID_SNR_THRESHOLD, 4 },
		{ SI468X_PROP_AM_VALID_HDLEVEL_THRESHOLD, 0 },
		{ SI468X_PROP_AM_RSQ_INTERRUPT_SOURCE, 0 },
		{ SI468X_PROP_AM_RSQ_SNR_HIGH_THRESHOLD, 127 },
		{ SI468X_PROP_AM_RSQ_SNR_LOW_THRESHOLD, -128 },
		{ SI468X_PROP_AM_RSQ_RSSI_HIGH_THRESHOLD, 127 },
		{ SI468X_PROP_AM_RSQ_RSSI_LOW_THRESHOLD, -128 },
		{ SI468X_PROP_AM_RSQ_HD_DETECTION, 48 },
		{ SI468X_PROP_AM_RSQ_HD_LEVEL_TIME_CONST, 32 },
		{ SI468X_PROP_AM_RSQ_HDDETECTED_THD, 0x1e1e },
		{ SI468X_PROP_AM_RSQ_HDLEVEL_HIGH_THRESHOLD, 100 },
		{ SI468X_PROP_AM_RSQ_HDLEVEL_LOW_THRESHOLD, 0 },
		{ SI468X_PROP_AM_ACF_INTERRUPT_SOURCE, 0 },
		{ SI468X_PROP_AM_ACF_SOFTMUTE_THRESHOLD, 31 },
		{ SI468X_PROP_AM_ACF_HIGHCUT_THRESHOLD, 0 },
		{ SI468X_PROP_AM_ACF_SOFTMUTE_TOLERANCE, 2 },
		{ SI468X_PROP_AM_ACF_HIGHCUT_TOLERANCE, 20 },
		{ SI468X_PROP_AM_ACF_CONTROL_SOURCE, 0 },
		{ SI468X_PROP_AM_SOFTMUTE_SQ_LIMITS, 0x0800 },
		{ SI468X_PROP_AM_SOFTMUTE_SQ_ATTENUATION, 0x000c },
		{ SI468X_PROP_AM_SOFTMUTE_SQ_ATTACK_TIME, 120 },
		{ SI468X_PROP_AM_SOFTMUTE_SQ_RELEASE_TIME, 500 },
		{ SI468X_PROP_AM_HIGHCUT_SQ_LIMITS, 0x0a06 },
		{ SI468X_PROP_AM_HIGHCUT_SQ_CUTOFF_FREQ, 0x280a },
		{ SI468X_PROP_AM_HIGHCUT_SQ_ATTACK_TIME, 16 },
		{ SI468X_PROP_AM_HIGHCUT_SQ_RELEASE_TIME, 2000 },
		{ SI468X_PROP_AM_DEMOD_AFC_RANGE, 0x0000 },
		{ SI468X_PROP_HD_BLEND_OPTIONS, 0x000a },
		{ SI468X_PROP_HD_BLEND_ANALOG_TO_HD_TRANSITION_TIME, 750 },
		{ SI468X_PROP_HD_BLEND_HD_TO_ANALOG_TRANSITION_TIME, 100 },
		{ SI468X_PROP_HD_BLEND_DYNAMIC_GAIN, 0 },
		{ SI468X_PROP_HD_BLEND_DECISION_ANA_TO_DIG_THRESHOLD, 67 },
		{ SI468X_PROP_HD_BLEND_DECISION_ANA_TO_DIG_DELAY, 5000 },
		{ SI468X_PROP_HD_BLEND_SERV_LOSS_RAMP_UP_TIME, 750 },
		{ SI468X_PROP_HD_BLEND_SERV_LOSS_RAMP_DOWN_TIME, 250 },
		{ SI468X_PROP_HD_BLEND_SERV_LOSS_NOISE_RAMP_UP_TIME, 1000 },
		{ SI468X_PROP_HD_BLEND_SERV_LOSS_NOISE_RAMP_DOWN_TIME, 250 },
		{ SI468X_PROP_HD_BLEND_SERV_LOSS_NOISE_LEVEL, 512 },
		{ SI468X_PROP_HD_BLEND_SERV_LOSS_NOISE_DAAI_THRESHOLD, 30 },
		{ SI468X_PROP_HD_BLEND_SERV_LOSS_NOISE_AUDIO_START_DELAY, 4 },
		{ SI468X_PROP_HD_BLEND_BWM_CTRL_THRES, 0x003c },
		{ SI468X_PROP_HD_BLEND_BWM_CTRL_LEVEL, 0x9628 },
		{ SI468X_PROP_HD_BLEND_BWM_CTRL_RAMP_UP_TIME, 5000 },
		{ SI468X_PROP_HD_BLEND_BWM_CTRL_RAMP_DOWN_TIME, 200 },
		{ SI468X_PROP_HD_BLEND_BWM_BLEND_THRES, 0x0032 },
		{ SI468X_PROP_HD_BLEND_BWM_BLEND_LEVEL, 0x7f00 },
		{ SI468X_PROP_HD_BLEND_BWM_BLEND_RAMP_UP_TIME, 400 },
		{ SI468X_PROP_HD_BLEND_BWM_BLEND_RAMP_DOWN_TIME, 16 },
		{ SI468X_PROP_HD_DIGRAD_INTERRUPT_SOURCE, 0 },
		{ SI468X_PROP_HD_DIGRAD_CDNR_LOW_THRESHOLD, 0 },
		{ SI468X_PROP_HD_DIGRAD_CDNR_HIGH_THRESHOLD, 127 },
		{ SI468X_PROP_HD_EVENT_INTERRUPT_SOURCE, 0 },
		{ SI468X_PROP_HD_EVENT_SIS_CONFIG, 0x0017 },
		{ SI468X_PROP_HD_EVENT_ALERT_CONFIG, 0x0001 },
		{ SI468X_PROP_HD_ACF_INTERRUPT_SOURCE, 0 },
		{ SI468X_PROP_HD_ACF_COMF_NOISE_THRESHOLD, 512 },
		{ SI468X_PROP_HD_ACF_AUDIO_BW_THRESHOLD, 40 },
		{ SI468X_PROP_HD_ACF_STEREO_SEP_THRESHOLD, 0 },
		{ SI468X_PROP_HD_ACF_COMF_NOISE_TOLERANCE, 5 },
		{ SI468X_PROP_HD_ACF_AUDIO_BW_TOLERANCE, 2 },
		{ SI468X_PROP_HD_ACF_STEREO_SEP_TOLERANCE, 5 },
		{ SI468X_PROP_HD_PSD_ENABLE, 0 },
		{ SI468X_PROP_HD_PSD_FIELD_MASK, 0xffff },
		{ SI468X_PROP_HD_AUDIO_CTRL_FRAME_DELAY, 6 },
		{ SI468X_PROP_HD_AUDIO_CTRL_PROGRAM_LOSS_THRESHOLD, 0 },
		{ SI468X_PROP_HD_AUDIO_CTRL_BALL_GAME_ENABLE, 1 },
		{ SI468X_PROP_HD_CODEC_MODE_0_BLEND_THRESHOLD, 3 },
		{ SI468X_PROP_HD_CODEC_MODE_0_SAMPLES_DELAY, 0 },
		{ SI468X_PROP_HD_CODEC_MODE_0_BLEND_RATE, 1 },
		{ SI468X_PROP_HD_CODEC_MODE_2_BLEND_THRESHOLD, 3 },
		{ SI468X_PROP_HD_CODEC_MODE_2_SAMPLES_DELAY, 7376 },
		{ SI468X_PROP_HD_CODEC_MODE_2_BLEND_RATE, 1 },
		{ SI468X_PROP_HD_CODEC_MODE_10_BLEND_THRESHOLD, 3 },
		{ SI468X_PROP_HD_CODEC_MODE_10_SAMPLES_DELAY, 0 },
		{ SI468X_PROP_HD_CODEC_MODE_10_BLEND_RATE, 1 },
		{ SI468X_PROP_HD_CODEC_MODE_13_BLEND_THRESHOLD, 3 },
		{ SI468X_PROP_HD_CODEC_MODE_13_SAMPLES_DELAY, 0 },
		{ SI468X_PROP_HD_CODEC_MODE_13_BLEND_RATE, 1 },
		{ SI468X_PROP_HD_CODEC_MODE_1_BLEND_THRESHOLD, 3 },
		{ SI468X_PROP_HD_CODEC_MODE_1_SAMPLES_DELAY, 0 },
		{ SI468X_PROP_HD_CODEC_MODE_1_BLEND_RATE, 1 },
		{ SI468X_PROP_HD_CODEC_MODE_3_BLEND_THRESHOLD, 3 },
		{ SI468X_PROP_HD_CODEC_MODE_3_SAMPLES_DELAY, 0 },
		{ SI468X_PROP_HD_CODEC_MODE_3_BLEND_RATE, 1 },
		{ SI468X_PROP_HD_EZBLEND_ENABLE, 0 },
		{ SI468X_PROP_HD_EZBLEND_MPS_BLEND_THRESHOLD, 3 },
		{ SI468X_PROP_HD_EZBLEND_MPS_BLEND_RATE, 3 },
		{ SI468X_PROP_HD_EZBLEND_MPS_SAMPLES_DELAY, 7376 },
		{ SI468X_PROP_HD_EZBLEND_SPS_BLEND_THRESHOLD, 3 },
		{ SI468X_PROP_HD_EZBLEND_SPS_BLEND_RATE, 1 },
		{ SI468X_PROP_HD_ENHANCED_STREAM_HOLDOFF_CONFIG, 0 },
		{ SI468X_PROP_HD_ENHANCED_STREAM_HOLDOFF_THRESHOLDS, 0x2f2f },
		{ SI468X_PROP_HD_TEST_BER_CONFIG, 0 },
};

static const struct regmap_range si468x_fm_reg_ranges[] = {
		regmap_reg_range(SI468X_PROP_AGC_RF_THRESHOLD,
			SI468X_PROP_AGC_RF_THRESHOLD),
		regmap_reg_range(SI468X_PROP_FM_TUNE_FE_VARM,
			SI468X_PROP_FM_TUNE_FE_CFG),
		regmap_reg_range(SI468X_PROP_FM_SEEK_BAND_BOTTOM,
			SI468X_PROP_FM_SEEK_FREQUENCY_SPACING),
		regmap_reg_range(SI468X_PROP_FM_VALID_MAX_TUNE_ERROR,
			SI468X_PROP_FM_VALID_SNR_THRESHOLD),
		regmap_reg_range(SI468X_PROP_FM_VALID_HDLEVEL_THRESHOLD,
			SI468X_PROP_FM_VALID_HDLEVEL_THRESHOLD),
		regmap_reg_range(SI468X_PROP_FM_RSQ_INTERRUPT_SOURCE,
			SI468X_PROP_FM_RSQ_RSSI_LOW_THRESHOLD),
		regmap_reg_range(SI468X_PROP_FM_RSQ_HD_DETECTION,
			SI468X_PROP_FM_RSQ_HDLEVEL_LOW_THRESHOLD),
		regmap_reg_range(SI468X_PROP_FM_ACF_INTERRUPT_SOURCE,
			SI468X_PROP_FM_ACF_BLEND_TOLERANCE),
		regmap_reg_range(SI468X_PROP_FM_SOFTMUTE_SNR_LIMITS,
			SI468X_PROP_FM_SOFTMUTE_SNR_RELEASE_TIME),
		regmap_reg_range(SI468X_PROP_FM_HIGHCUT_RSSI_LIMITS,
			SI468X_PROP_FM_HIGHCUT_MULTIPATH_RELEASE_TIME),
		regmap_reg_range(SI468X_PROP_FM_BLEND_RSSI_LIMITS,
			SI468X_PROP_FM_BLEND_RSSI_LIMITS),
		regmap_reg_range(SI468X_PROP_FM_BLEND_RSSI_ATTACK_TIME,
			SI468X_PROP_FM_BLEND_SNR_LIMITS),
		regmap_reg_range(SI468X_PROP_FM_BLEND_SNR_ATTACK_TIME,
			SI468X_PROP_FM_BLEND_MULTIPATH_LIMITS),
		regmap_reg_range(SI468X_PROP_FM_BLEND_MULTIPATH_ATTACK_TIME,
			SI468X_PROP_FM_BLEND_MULTIPATH_RELEASE_TIME),
		regmap_reg_range(SI468X_PROP_FM_AUDIO_DE_EMPHASIS,
			SI468X_PROP_FM_AUDIO_DE_EMPHASIS),
		regmap_reg_range(SI468X_PROP_FM_RDS_INTERRUPT_SOURCE,
			SI468X_PROP_FM_RDS_CONFIDENCE),
		regmap_reg_range(SI468X_PROP_HD_BLEND_OPTIONS,
			SI468X_PROP_HD_BLEND_HD_TO_ANALOG_TRANSITION_TIME),
		regmap_reg_range(SI468X_PROP_HD_BLEND_DYNAMIC_GAIN,
			SI468X_PROP_HD_BLEND_DYNAMIC_GAIN),
		regmap_reg_range(SI468X_PROP_HD_BLEND_DECISION_ANA_TO_DIG_THRESHOLD,
			SI468X_PROP_HD_BLEND_SERV_SWITCH_RAMP_DOWN_TIME),
		regmap_reg_range(SI468X_PROP_HD_DIGRAD_INTERRUPT_SOURCE,
			SI468X_PROP_HD_DIGRAD_CDNR_HIGH_THRESHOLD),
		regmap_reg_range(SI468X_PROP_HD_EVENT_INTERRUPT_SOURCE,
			SI468X_PROP_HD_EVENT_ALERT_CONFIG),
		regmap_reg_range(SI468X_PROP_HD_ACF_INTERRUPT_SOURCE,
			SI468X_PROP_HD_ACF_COMF_NOISE_THRESHOLD),
		regmap_reg_range(SI468X_PROP_HD_ACF_COMF_NOISE_TOLERANCE,
			SI468X_PROP_HD_ACF_COMF_NOISE_TOLERANCE),
		regmap_reg_range(SI468X_PROP_HD_PSD_ENABLE,
			SI468X_PROP_HD_PSD_FIELD_MASK),
		regmap_reg_range(SI468X_PROP_HD_AUDIO_CTRL_FRAME_DELAY,
			SI468X_PROP_HD_AUDIO_CTRL_BALL_GAME_ENABLE),
		regmap_reg_range(SI468X_PROP_HD_CODEC_MODE_0_BLEND_THRESHOLD,
			SI468X_PROP_HD_CODEC_MODE_3_BLEND_RATE),
		regmap_reg_range(SI468X_PROP_HD_EZBLEND_ENABLE,
			SI468X_PROP_HD_EZBLEND_SPS_BLEND_RATE),
		regmap_reg_range(SI468X_PROP_HD_TEST_BER_CONFIG,
			SI468X_PROP_HD_TEST_DEBUG_AUDIO),
};

static const struct regmap_access_table si468x_fm_write_ranges_table = {
		.yes_ranges     = si468x_fm_reg_ranges,
		.n_yes_ranges   = ARRAY_SIZE(si468x_fm_reg_ranges),
};

static const struct reg_default si468x_fm_reg_defaults[] = {
		{ SI468X_PROP_AGC_RF_THRESHOLD, 0 },
		{ SI468X_PROP_FM_TUNE_FE_VARM, 0 },
		{ SI468X_PROP_FM_TUNE_FE_VARB, 0 },
		{ SI468X_PROP_FM_TUNE_FE_CFG, 0x0000 },
		{ SI468X_PROP_FM_SEEK_BAND_BOTTOM, 8750 },
		{ SI468X_PROP_FM_SEEK_BAND_TOP, 10790 },
		{ SI468X_PROP_FM_SEEK_FREQUENCY_SPACING, 10 },
		{ SI468X_PROP_FM_VALID_MAX_TUNE_ERROR, 114 },
		{ SI468X_PROP_FM_VALID_RSSI_TIME, 15 },
		{ SI468X_PROP_FM_VALID_RSSI_THRESHOLD, 17 },
		{ SI468X_PROP_FM_VALID_SNR_TIME, 40 },
		{ SI468X_PROP_FM_VALID_SNR_THRESHOLD, 10 },
		{ SI468X_PROP_FM_VALID_HDLEVEL_THRESHOLD, 0 },
		{ SI468X_PROP_FM_RSQ_INTERRUPT_SOURCE, 0 },
		{ SI468X_PROP_FM_RSQ_SNR_HIGH_THRESHOLD, 127 },
		{ SI468X_PROP_FM_RSQ_SNR_LOW_THRESHOLD, -128 },
		{ SI468X_PROP_FM_RSQ_RSSI_HIGH_THRESHOLD, 127 },
		{ SI468X_PROP_FM_RSQ_RSSI_LOW_THRESHOLD, -128 },
		{ SI468X_PROP_FM_RSQ_HD_DETECTION, 0x000d },
		{ SI468X_PROP_FM_RSQ_HD_LEVEL_TIME_CONST, 32 },
		{ SI468X_PROP_FM_RSQ_HDDETECTED_THD, 0x1e1e },
		{ SI468X_PROP_FM_RSQ_HDLEVEL_HIGH_THRESHOLD, 100 },
		{ SI468X_PROP_FM_RSQ_HDLEVEL_LOW_THRESHOLD, 0 },
		{ SI468X_PROP_FM_ACF_INTERRUPT_SOURCE, 0 },
		{ SI468X_PROP_FM_ACF_SOFTMUTE_THRESHOLD, 31 },
		{ SI468X_PROP_FM_ACF_HIGHCUT_THRESHOLD, 0 },
		{ SI468X_PROP_FM_ACF_BLEND_THRESHOLD, 0 },
		{ SI468X_PROP_FM_ACF_SOFTMUTE_TOLERANCE, 2 },
		{ SI468X_PROP_FM_ACF_HIGHCUT_TOLERANCE, 20 },
		{ SI468X_PROP_FM_ACF_BLEND_TOLERANCE, 5 },
		{ SI468X_PROP_FM_SOFTMUTE_SNR_LIMITS, 0x0602 },
		{ SI468X_PROP_FM_SOFTMUTE_SNR_ATTENUATION, 0x0008 },
		{ SI468X_PROP_FM_SOFTMUTE_SNR_ATTACK_TIME, 16 },
		{ SI468X_PROP_FM_SOFTMUTE_SNR_RELEASE_TIME, 4000 },
		{ SI468X_PROP_FM_HIGHCUT_RSSI_LIMITS, 0x0c06 },
		{ SI468X_PROP_FM_HIGHCUT_RSSI_CUTOFF_FREQ, 0xc828 },
		{ SI468X_PROP_FM_HIGHCUT_RSSI_ATTACK_TIME, 16 },
		{ SI468X_PROP_FM_HIGHCUT_RSSI_RELEASE_TIME, 4000 },
		{ SI468X_PROP_FM_HIGHCUT_SNR_LIMITS, 0x0903 },
		{ SI468X_PROP_FM_HIGHCUT_SNR_CUTOFF_FREQ, 0xc828 },
		{ SI468X_PROP_FM_HIGHCUT_SNR_ATTACK_TIME, 16 },
		{ SI468X_PROP_FM_HIGHCUT_SNR_RELEASE_TIME, 4000 },
		{ SI468X_PROP_FM_HIGHCUT_MULTIPATH_LIMITS, 0x2d3c },
		{ SI468X_PROP_FM_HIGHCUT_MULTIPATH_CUTOFF_FREQ, 0xc828 },
		{ SI468X_PROP_FM_HIGHCUT_MULTIPATH_ATTACK_TIME, 16 },
		{ SI468X_PROP_FM_HIGHCUT_MULTIPATH_RELEASE_TIME, 4000 },
		{ SI468X_PROP_FM_BLEND_RSSI_LIMITS, 0x2010 },
		{ SI468X_PROP_FM_BLEND_RSSI_ATTACK_TIME, 16 },
		{ SI468X_PROP_FM_BLEND_RSSI_RELEASE_TIME, 4000 },
		{ SI468X_PROP_FM_BLEND_SNR_LIMITS, 0x180f },
		{ SI468X_PROP_FM_BLEND_SNR_ATTACK_TIME, 16 },
		{ SI468X_PROP_FM_BLEND_SNR_RELEASE_TIME, 4000 },
		{ SI468X_PROP_FM_BLEND_MULTIPATH_LIMITS, 0x2d3c },
		{ SI468X_PROP_FM_BLEND_MULTIPATH_ATTACK_TIME, 16 },
		{ SI468X_PROP_FM_BLEND_MULTIPATH_RELEASE_TIME, 4000 },
		{ SI468X_PROP_FM_AUDIO_DE_EMPHASIS, 0 },
		{ SI468X_PROP_FM_RDS_INTERRUPT_SOURCE, 0x0000 },
		{ SI468X_PROP_FM_RDS_INTERRUPT_FIFO_COUNT, 0x0000 },
		{ SI468X_PROP_FM_RDS_CONFIG, 0x0000 },
		{ SI468X_PROP_FM_RDS_CONFIDENCE, 0x1111 },
		{ SI468X_PROP_HD_BLEND_OPTIONS, 0x000a },
		{ SI468X_PROP_HD_BLEND_ANALOG_TO_HD_TRANSITION_TIME, 750 },
		{ SI468X_PROP_HD_BLEND_HD_TO_ANALOG_TRANSITION_TIME, 100 },
		{ SI468X_PROP_HD_BLEND_DYNAMIC_GAIN, 0 },
		{ SI468X_PROP_HD_BLEND_DECISION_ANA_TO_DIG_THRESHOLD, 58 },
		{ SI468X_PROP_HD_BLEND_DECISION_ANA_TO_DIG_DELAY, 5000 },
		{ SI468X_PROP_HD_BLEND_SERV_LOSS_RAMP_UP_TIME, 750 },
		{ SI468X_PROP_HD_BLEND_SERV_LOSS_RAMP_DOWN_TIME, 250 },
		{ SI468X_PROP_HD_BLEND_SERV_LOSS_NOISE_RAMP_UP_TIME, 1000 },
		{ SI468X_PROP_HD_BLEND_SERV_LOSS_NOISE_RAMP_DOWN_TIME, 250 },
		{ SI468X_PROP_HD_BLEND_SERV_LOSS_NOISE_LEVEL, 512 },
		{ SI468X_PROP_HD_BLEND_SERV_LOSS_NOISE_DAAI_THRESHOLD, 40 },
		{ SI468X_PROP_HD_BLEND_SERV_LOSS_NOISE_AUDIO_START_DELAY, 4 },
		{ SI468X_PROP_HD_BLEND_SERV_SWITCH_RAMP_UP_TIME, 184 },
		{ SI468X_PROP_HD_BLEND_SERV_SWITCH_RAMP_DOWN_TIME, 184 },
		{ SI468X_PROP_HD_DIGRAD_INTERRUPT_SOURCE, 0 },
		{ SI468X_PROP_HD_DIGRAD_CDNR_LOW_THRESHOLD, 0 },
		{ SI468X_PROP_HD_DIGRAD_CDNR_HIGH_THRESHOLD, 127 },
		{ SI468X_PROP_HD_EVENT_INTERRUPT_SOURCE, 0 },
		{ SI468X_PROP_HD_EVENT_SIS_CONFIG, 0x0017 },
		{ SI468X_PROP_HD_EVENT_ALERT_CONFIG, 0x0001 },
		{ SI468X_PROP_HD_ACF_INTERRUPT_SOURCE, 0 },
		{ SI468X_PROP_HD_ACF_COMF_NOISE_THRESHOLD, 512 },
		{ SI468X_PROP_HD_ACF_COMF_NOISE_TOLERANCE, 5 },
		{ SI468X_PROP_HD_PSD_ENABLE, 0 },
		{ SI468X_PROP_HD_PSD_FIELD_MASK, 0xffff },
		{ SI468X_PROP_HD_AUDIO_CTRL_FRAME_DELAY, 6 },
		{ SI468X_PROP_HD_AUDIO_CTRL_PROGRAM_LOSS_THRESHOLD, 0 },
		{ SI468X_PROP_HD_AUDIO_CTRL_BALL_GAME_ENABLE, 1 },
		{ SI468X_PROP_HD_CODEC_MODE_0_BLEND_THRESHOLD, 3 },
		{ SI468X_PROP_HD_CODEC_MODE_0_SAMPLES_DELAY, 3697 },
		{ SI468X_PROP_HD_CODEC_MODE_0_BLEND_RATE, 1 },
		{ SI468X_PROP_HD_CODEC_MODE_2_BLEND_THRESHOLD, 3 },
		{ SI468X_PROP_HD_CODEC_MODE_2_SAMPLES_DELAY, 0 },
		{ SI468X_PROP_HD_CODEC_MODE_2_BLEND_RATE, 1 },
		{ SI468X_PROP_HD_CODEC_MODE_10_BLEND_THRESHOLD, 3 },
		{ SI468X_PROP_HD_CODEC_MODE_10_SAMPLES_DELAY, 0 },
		{ SI468X_PROP_HD_CODEC_MODE_10_BLEND_RATE, 1 },
		{ SI468X_PROP_HD_CODEC_MODE_13_BLEND_THRESHOLD, 3 },
		{ SI468X_PROP_HD_CODEC_MODE_13_SAMPLES_DELAY, 0 },
		{ SI468X_PROP_HD_CODEC_MODE_13_BLEND_RATE, 1 },
		{ SI468X_PROP_HD_CODEC_MODE_1_BLEND_THRESHOLD, 3 },
		{ SI468X_PROP_HD_CODEC_MODE_1_SAMPLES_DELAY, 0 },
		{ SI468X_PROP_HD_CODEC_MODE_1_BLEND_RATE, 1 },
		{ SI468X_PROP_HD_CODEC_MODE_3_BLEND_THRESHOLD, 3 },
		{ SI468X_PROP_HD_CODEC_MODE_3_SAMPLES_DELAY, 0 },
		{ SI468X_PROP_HD_CODEC_MODE_3_BLEND_RATE, 1 },
		{ SI468X_PROP_HD_SERVICE_MODE_CONTROL_MP11_ENABLE, 0x0000 },
		{ SI468X_PROP_HD_EZBLEND_ENABLE, 0 },
		{ SI468X_PROP_HD_EZBLEND_MPS_BLEND_THRESHOLD, 3 },
		{ SI468X_PROP_HD_EZBLEND_MPS_BLEND_RATE, 3 },
		{ SI468X_PROP_HD_EZBLEND_MPS_SAMPLES_DELAY, 3697 },
		{ SI468X_PROP_HD_EZBLEND_SPS_BLEND_THRESHOLD, 4 },
		{ SI468X_PROP_HD_EZBLEND_SPS_BLEND_RATE, 1 },
		{ SI468X_PROP_HD_TEST_BER_CONFIG, 0 },
		{ SI468X_PROP_HD_TEST_DEBUG_AUDIO, 0 },
};

static const struct regmap_range si468x_dab_reg_ranges[] = {
		regmap_reg_range(SI468X_PROP_DAB_TUNE_FE_VARM,
			SI468X_PROP_DAB_TUNE_FE_CFG),
		regmap_reg_range(SI468X_PROP_DAB_DIGRAD_INTERRUPT_SOURCE,
			SI468X_PROP_DAB_DIGRAD_RSSI_LOW_THRESHOLD),
		regmap_reg_range(SI468X_PROP_DAB_VALID_RSSI_TIME,
			SI468X_PROP_DAB_VALID_DETECT_TIME),
		regmap_reg_range(SI468X_PROP_DAB_EVENT_INTERRUPT_SOURCE,
			SI468X_PROP_DAB_EVENT_MIN_FREQINFO_PERIOD),
		regmap_reg_range(SI468X_PROP_DAB_XPAD_ENABLE,
			SI468X_PROP_DAB_DRC_OPTION),
		regmap_reg_range(SI468X_PROP_DAB_ACF_ENABLE,
			SI468X_PROP_DAB_ACF_MUTE_SIGLOSS_THRESHOLD),
		regmap_reg_range(SI468X_PROP_DAB_ACF_SOFTMUTE_BER_LIMITS,
			SI468X_PROP_DAB_ACF_CMFTNOISE_RELEASE_TIME),
		regmap_reg_range(SI468X_PROP_DAB_ANNOUNCEMENT_ENABLE,
			SI468X_PROP_DAB_ANNOUNCEMENT_ENABLE),
		regmap_reg_range(SI468X_PROP_DAB_TEST_BER_CONFIG,
			SI468X_PROP_DAB_TEST_BER_CONFIG),
};

static const struct regmap_access_table si468x_dab_write_ranges_table = {
		.yes_ranges     = si468x_dab_reg_ranges,
		.n_yes_ranges   = ARRAY_SIZE(si468x_dab_reg_ranges),
};

static const struct reg_default si468x_dab_reg_defaults[] = {
		{ SI468X_PROP_DAB_TUNE_FE_VARM, 0 },
		{ SI468X_PROP_DAB_TUNE_FE_VARB, 0 },
		{ SI468X_PROP_DAB_TUNE_FE_CFG, 0x0001 },
		{ SI468X_PROP_DAB_DIGRAD_INTERRUPT_SOURCE, 0 },
		{ SI468X_PROP_DAB_DIGRAD_RSSI_HIGH_THRESHOLD, 127 },
		{ SI468X_PROP_DAB_DIGRAD_RSSI_LOW_THRESHOLD, -128 },
		{ SI468X_PROP_DAB_VALID_RSSI_TIME, 30 },
		{ SI468X_PROP_DAB_VALID_RSSI_THRESHOLD, 12 },
		{ SI468X_PROP_DAB_VALID_ACQ_TIME, 2000 },
		{ SI468X_PROP_DAB_VALID_SYNC_TIME, 1200 },
		{ SI468X_PROP_DAB_VALID_DETECT_TIME, 35 },
		{ SI468X_PROP_DAB_EVENT_INTERRUPT_SOURCE, 0 },
		{ SI468X_PROP_DAB_EVENT_MIN_SVRLIST_PERIOD, 10 },
		{ SI468X_PROP_DAB_EVENT_MIN_SVRLIST_PERIOD_RECONFIG, 10 },
		{ SI468X_PROP_DAB_EVENT_MIN_FREQINFO_PERIOD, 5 },
		{ SI468X_PROP_DAB_XPAD_ENABLE, 1 },
		{ SI468X_PROP_DAB_DRC_OPTION, 0 },
		{ SI468X_PROP_DAB_ACF_ENABLE, 3 },
		{ SI468X_PROP_DAB_ACF_MUTE_SIGLOSS_THRESHOLD, 6 },
		{ SI468X_PROP_DAB_ACF_SOFTMUTE_BER_LIMITS, 0xe2a6 },
		{ SI468X_PROP_DAB_ACF_SOFTMUTE_ATTENUATION_LEVEL, 80 },
		{ SI468X_PROP_DAB_ACF_SOFTMUTE_ATTACK_TIME, 100 },
		{ SI468X_PROP_DAB_ACF_SOFTMUTE_RELEASE_TIME, 4000 },
		{ SI468X_PROP_DAB_ACF_CMFTNOISE_BER_LIMITS, 0xe2a6 },
		{ SI468X_PROP_DAB_ACF_CMFTNOISE_LEVEL, 0x200 },
		{ SI468X_PROP_DAB_ACF_CMFTNOISE_ATTACK_TIME, 100 },
		{ SI468X_PROP_DAB_ACF_CMFTNOISE_RELEASE_TIME, 4000 },
		{ SI468X_PROP_DAB_ANNOUNCEMENT_ENABLE, 0x07ff },
		{ SI468X_PROP_DAB_TEST_BER_CONFIG, 0 },
};

static int si468x_core_regmap_write(void *context, unsigned int reg,
			unsigned int val)
{
	struct si468x_core *core = context;
	int err;

	err = si468x_core_cmd_set_property(core, reg, val);
	if (err < 0)
		return err;

	return 0;
}

static int si468x_core_regmap_read(void *context, unsigned int reg,
			unsigned int *val)
{
	struct si468x_core *core = context;
	int err;

	err = si468x_core_cmd_get_property(core, reg);
	if (err < 0)
		return err;

	*val = err;

	return 0;
}

static const struct regmap_config si468x_common_regmap_config = {
		.name = "si468x_common",
		.reg_bits = 16,
		.val_bits = 16,
		.max_register = SI468X_PROP_DIGITAL_SERVICE_RESTART_DELAY + 1,
		.wr_table = &si468x_common_write_ranges_table,
		.reg_read = si468x_core_regmap_read,
		.reg_write = si468x_core_regmap_write,
		.reg_defaults = si468x_common_reg_defaults,
		.num_reg_defaults = ARRAY_SIZE(si468x_common_reg_defaults),
		.cache_type = REGCACHE_RBTREE,
};

static const struct regmap_config si468x_am_regmap_config = {
		.name = "si468x_am",
		.reg_bits = 16,
		.val_bits = 16,
		.max_register = SI468X_PROP_HD_TEST_BER_CONFIG + 1,
		.wr_table = &si468x_am_write_ranges_table,
		.reg_read = si468x_core_regmap_read,
		.reg_write = si468x_core_regmap_write,
		.reg_defaults = si468x_am_reg_defaults,
		.num_reg_defaults = ARRAY_SIZE(si468x_am_reg_defaults),
		.cache_type = REGCACHE_RBTREE,
};

static const struct regmap_config si468x_fm_regmap_config = {
		.name = "si468x_fm",
		.reg_bits = 16,
		.val_bits = 16,
		.max_register = SI468X_PROP_HD_TEST_DEBUG_AUDIO + 1,
		.wr_table = &si468x_fm_write_ranges_table,
		.reg_read = si468x_core_regmap_read,
		.reg_write = si468x_core_regmap_write,
		.reg_defaults = si468x_fm_reg_defaults,
		.num_reg_defaults = ARRAY_SIZE(si468x_fm_reg_defaults),
		.cache_type = REGCACHE_RBTREE,
};

static const struct regmap_config si468x_dab_regmap_config = {
		.name = "si468x_dab",
		.reg_bits = 16,
		.val_bits = 16,
		.max_register = SI468X_PROP_DAB_TEST_BER_CONFIG + 1,
		.wr_table = &si468x_dab_write_ranges_table,
		.reg_read = si468x_core_regmap_read,
		.reg_write = si468x_core_regmap_write,
		.reg_defaults = si468x_dab_reg_defaults,
		.num_reg_defaults = ARRAY_SIZE(si468x_dab_reg_defaults),
		.cache_type = REGCACHE_RBTREE,
};

int devm_regmap_init_si468x(struct si468x_core *core)
{
	u16 fm_tune_fe_varm;
	u16 fm_tune_fe_varb;
	u16 fm_tune_fe_cfg;
	u16 dab_tune_fe_varm;
	u16 dab_tune_fe_varb;
	u16 dab_tune_fe_cfg;

	core->regmap_common = devm_regmap_init(core->dev, NULL,
				core, &si468x_common_regmap_config);
	if (IS_ERR(core->regmap_common))
		return PTR_ERR(core->regmap_common);
	regcache_mark_dirty(core->regmap_common);
	regcache_cache_only(core->regmap_common, true);

	core->regmap_fm = devm_regmap_init(core->dev, NULL,
				core, &si468x_fm_regmap_config);
	if (IS_ERR(core->regmap_fm))
		return PTR_ERR(core->regmap_fm);
	regcache_mark_dirty(core->regmap_fm);
	regcache_cache_only(core->regmap_fm, true);
	if (!of_property_read_u16((core->dev)->of_node,
			"fm_tune_fe_varm",
			&fm_tune_fe_varm))
		if (regmap_write(core->regmap_fm,
				SI468X_PROP_FM_TUNE_FE_VARM,
				fm_tune_fe_varm) < 0)
			dev_err(core->dev, "Failed to set fm_tune_fe_varm");
	if (!of_property_read_u16((core->dev)->of_node,
			"fm_tune_fe_varb",
			&fm_tune_fe_varb))
		if (regmap_write(core->regmap_fm,
				SI468X_PROP_FM_TUNE_FE_VARB,
				fm_tune_fe_varb) < 0)
			dev_err(core->dev, "Failed to set fm_tune_fe_varb");
	if (!of_property_read_u16((core->dev)->of_node,
			"fm_tune_fe_cfg",
			&fm_tune_fe_cfg))
		if (regmap_write(core->regmap_fm,
				SI468X_PROP_FM_TUNE_FE_CFG,
				fm_tune_fe_cfg) < 0)
			dev_err(core->dev, "Failed to set fm_tune_fe_cfg");

	if (core->si468x_device_info->has_am) {
		core->regmap_am = devm_regmap_init(core->dev, NULL,
					core, &si468x_am_regmap_config);
		if (IS_ERR(core->regmap_am))
			return PTR_ERR(core->regmap_am);
		regcache_mark_dirty(core->regmap_am);
		regcache_cache_only(core->regmap_am, true);
	}

	if (core->si468x_device_info->has_dab) {
		core->regmap_dab = devm_regmap_init(core->dev, NULL,
					core, &si468x_dab_regmap_config);
		if (IS_ERR(core->regmap_dab))
			return PTR_ERR(core->regmap_dab);
		regcache_mark_dirty(core->regmap_dab);
		regcache_cache_only(core->regmap_dab, true);
		if (!of_property_read_u16((core->dev)->of_node,
				"dab_tune_fe_varm",
				&dab_tune_fe_varm))
			if (regmap_write(core->regmap_dab,
					SI468X_PROP_DAB_TUNE_FE_VARM,
					dab_tune_fe_varm) < 0)
				dev_err(core->dev, "Failed to set dab_tune_fe_varm");
		if (!of_property_read_u16((core->dev)->of_node,
				"dab_tune_fe_varb",
				&dab_tune_fe_varb))
			if (regmap_write(core->regmap_dab,
					SI468X_PROP_DAB_TUNE_FE_VARB,
					dab_tune_fe_varb) < 0)
				dev_err(core->dev, "Failed to set dab_tune_fe_varb");
		if (!of_property_read_u16((core->dev)->of_node,
				"dab_tune_fe_cfg",
				&dab_tune_fe_cfg))
			if (regmap_write(core->regmap_dab,
					SI468X_PROP_DAB_TUNE_FE_CFG,
					dab_tune_fe_cfg) < 0)
				dev_err(core->dev, "Failed to set dab_tune_fe_cfg");
	}
	return 0;
}
EXPORT_SYMBOL_GPL(devm_regmap_init_si468x);
